name: Fetch Data
on:
  push:
  workflow_dispatch:

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
    - name: RTT Sandy Request
      id: rttRequest
      uses: fjogeleit/http-request-action@master
      with:
        url: 'https://api.rtt.io/api/v1/json/search/SDY'
        method: 'GET'
        username: ${{ secrets.RTT_Username }}
        password: ${{ secrets.RTT_Password }}
    - name: Show Response
      run: echo ${{ steps.rttRequest.outputs.response }}

  writeToFile:
    runs-on: ubuntu-latest
    steps:
    - name: Write to file
      # You may pin to the exact commit or the version.
      # uses: frdrwrt/write-to-file@89c5761ba721d62b757edeefe02028e388885ab5
      uses: frdrwrt/write-to-file@v1.3
      with:
        # Where to create the file
        filepath: '/_data/test2.txt'# default is file
        # What to write to file
        content: "Test"
