name: Fetch Data
on:
  push:
  workflow_dispatch:

jobs:
  getData:
    runs-on: ubuntu-latest
    steps:
    - name: RTT Sandy Request
      id: rttRequest
      uses: fjogeleit/http-request-action@master
      with:
        url: 'https://api.rtt.io/api/v1/json/search/SDY'
        method: 'GET'
        username: ${{ secrets.RTT_Username }}
        password: ${{ secrets.RTT_Password }}
        
    - name: Show Response
      run: echo ${{ steps.rttRequest.outputs.response }}
    
jobs2:
  saveData:
    runs-on: ubuntu-latest
    steps:
          # If you need to, you can check out your repo to a different location
          - uses: actions/checkout@v2
            with:
              path: './pathToRepo/'

          # You can make whatever type of change to the repo...
          - run: echo "123" > ./pathToRepo/file.txt

          # ...and then use the action as you would normally do, but providing the path to the repo
          - uses: EndBug/add-and-commit@v7
            with:
              message: 'Add the very useful text file'
              add: '*.txt --force'
              cwd: './pathToRepo/'
    
