name: Fetch Data
on:
  push:
  workflow_dispatch:

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
    - name: RTT Sandy Request
      id: rttRequest
      uses: fjogeleit/http-request-action@master
      with:
        url: 'https://api.rtt.io/api/v1/json/search/SDY'
        method: 'GET'
        username: ${{ secrets.RTT_Username }}
        password: ${{ secrets.RTT_Password }}
    - name: Show Response
      run: echo ${{ steps.rttRequest.outputs.response }}
